### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.cdk/cache/notices.json'

### ISSUE THREAD

**Issue by ryanranft** [sportsdataverse/sportsdataverse-py#84]
I am working on configuring this repo in AWS codecatalyst and trying to perform a CDK deploy, I have configured workflows at my end where the CDK bootstrap was successful but the CDK deploy fails with below error -

=====
Failed to store notices in the cache: Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.cdk/cache/notices.json'

[06:33:59] Error: --app is required either in command-line, in cdk.json or in ~/.cdk.json
at execProgram (/tmp/opt/npm/lib/node_modules/aws-cdk/lib/index.js:469:48635)
at async CloudExecutable.synthesizer (/tmp/opt/npm/lib/node_modules/aws-cdk/lib/index.js:525:52237)
at async CloudExecutable.doSynthesize (/tmp/opt/npm/lib/node_modules/aws-cdk/lib/index.js:469:42230)
at async CloudExecutable.synthesize (/tmp/opt/npm/lib/node_modules/aws-cdk/lib/index.js:469:42023)
at async CdkToolkit.selectStacksForDeploy (/tmp/opt/npm/lib/node_modules/aws-cdk/lib/index.js:472:3462)
at async CdkToolkit.deploy (/tmp/opt/npm/lib/node_modules/aws-cdk/lib/index.js:470:176508)
at async exec4 (/tmp/opt/npm/lib/node_modules/aws-cdk/lib/index.js:525:53102)
--app is required either in command-line, in cdk.json or in ~/.cdk.json
--app is required either in command-line, in cdk.json or in ~/.cdk.json

::set-output name=ACTION_RUN_SUMMARY::[{text:CDK_DEPLOY_COMMAND_ERROR,level:Error,message:"The AWS CDK deploy action failed to perform one or more commands. Check the action logs for more information."}]
Error: The AWS CDK deploy action failed to perform one or more commands. Check the action logs for more information.

[Container] 2024/11/24 06:33:59.431265 Command failed with exit status 1
[Container] 2024/11/24 06:33:59.431324 Failed to run action due to exit status 1
=====

**Comment by akeaswaran** [comment]
`[06:33:59] Error: --app is required either in command-line, in cdk.json or in ~/.cdk.json` makes this seem like a CDK specific error rather than something coming from the repo? I am not familiar with CDK/CodeCatalyst myself, but I did a brief google for this error and after reading [some StackOverflow threads](https://stackoverflow.com/a/65428764), it seems like you may be missing a command (`app`) for CodeCatalyst to run. This repo doesn't have a `cdk.json` or any sort of command/script to run upfront, so it's possible that CodeCatalyst may not be the best choice here depending on your use case? 

Are you trying to make changes in the repo via CodeCatalyst or install the module in a different project? If the former, this might be of use, if you haven't come across it already: https://docs.aws.amazon.com/codecatalyst/latest/userguide/source-repositories-clone.html. If the latter, you can just need to add `sportsdataverse-py` to a `requirements.txt` file (this seems relevant to CodeCatalyst after a brief google: https://repost.aws/articles/ARBTATztMgQOeYyMZ9IAmxDw/configuring-codecatalyst-dev-environments).

**Comment by ryanranft** [comment]
This was an error on my end. Thanks!

**Comment by saiemgilani** [comment]
Closing this out - as @akeaswaran diagnosed and @ryanranft confirmed, this was an AWS CDK configuration issue in the reporter's own CodeCatalyst workflow rather than a defect in this package.

For the record: sportsdataverse-py is a pure-Python data-access library with no infrastructure component. There is no CDK app, no `cdk.json`, and no AWS deployment tooling anywhere in the repository - a repo-wide search for `cdk` across `*.py`, `*.json`, `*.yml`, `*.yaml`, and `*.toml` returns zero matches. Both errors in the traceback (`~/.cdk/cache/notices.json` and `--app is required either in command-line, in cdk.json or in ~/.cdk.json`) come from the `aws-cdk` CLI needing an app entry point it was not given.

Thanks for the follow-up confirming it was resolved on your end.
